name: Security Check

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.4
      with:
        always-auth: false
        node-version: '14.x' # Specify the Node.js version
        architecture: 'x64' # Specify the architecture
        
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v2
