name: Security Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - name: Secret Scan
        uses: actions/secrets-scan@v1
      - name: Dependency Review
        uses: github/dependency-review-action@v2
